### ISSUE TITLE
websis_lookup_profiles_path makes PATCH requests instead of POST

### ISSUE THREAD

**Issue by bunneyster** [pwnall/seven#50]
https://github.com/pwnall/seven/blob/master/config/routes.rb#L27

When editing a profile, the markup (https://github.com/pwnall/seven/blob/master/app/views/profiles/_fields.html.erb#L8) seems to suggest that a POST request should be made. Instead a PATCH request is being made.

**Comment by spark008** [comment]
Also, when I register a new user in development, it takes a really long time and the following error message is logged:

Net::LDAP::Error - Connection to ldap.mit.edu timed out.:
  net-ldap (0.11) lib/net/ldap/connection.rb:21:in `rescue in initialize'
  net-ldap (0.11) lib/net/ldap/connection.rb:12:in `initialize'
  net-ldap (0.11) lib/net/ldap.rb:1223:in `new_connection'
  net-ldap (0.11) lib/net/ldap.rb:672:in `block in open'
  net-ldap (0.11) lib/net/ldap/instrumentation.rb:19:in `instrument'
  net-ldap (0.11) lib/net/ldap.rb:670:in `open'
  net-ldap (0.11) lib/net/ldap.rb:606:in `open'
  app/models/email_resolver.rb:89:in `ldap_email_search'
  app/models/email_resolver.rb:74:in `resolve'
  app/models/email_resolver.rb:60:in `resolve'
  app/controllers/profiles_controller.rb:32:in `websis_lookup'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/abstract_controller/base.rb:183:in `process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal/rendering.rb:31:in `process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:119:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:498:in `block (2 levels) in compile'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:441:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:94:in `__run_callbacks__'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:742:in `_run_process_action_callbacks'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:83:in `run_callbacks'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/abstract_controller/callbacks.rb:19:in `process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal/rescue.rb:29:in `process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/notifications.rb:164:in `block in instrument'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/notifications.rb:164:in `instrument'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activerecord/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/abstract_controller/base.rb:128:in `process'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionview/lib/action_view/rendering.rb:30:in `process'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal.rb:189:in `dispatch'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_controller/metal.rb:261:in `dispatch'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/routing/route_set.rb:33:in `serve'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/journey/router.rb:42:in `block in serve'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/journey/router.rb:29:in `serve'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/routing/route_set.rb:714:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-noie-ce8313c6f327/lib/noie.rb:11:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionview/lib/action_view/digestor.rb:14:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/etag.rb:24:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/conditional_get.rb:38:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/head.rb:12:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/session/abstract/id.rb:220:in `context'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/session/abstract/id.rb:214:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/cookies.rb:593:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activerecord/lib/active_record/query_cache.rb:36:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:959:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activerecord/lib/active_record/migration.rb:453:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:90:in `__run_callbacks__'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:742:in `_run_call_callbacks'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/callbacks.rb:83:in `run_callbacks'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/reloader.rb:73:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/debug_exceptions.rb:48:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/railties/lib/rails/rack/logger.rb:42:in `call_app'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/railties/lib/rails/rack/logger.rb:24:in `block in call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/tagged_logging.rb:70:in `block in tagged'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/tagged_logging.rb:26:in `tagged'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/tagged_logging.rb:70:in `tagged'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/railties/lib/rails/rack/logger.rb:24:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/request_id.rb:24:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/method_override.rb:22:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/runtime.rb:20:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/activesupport/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/load_interlock.rb:13:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/actionpack/lib/action_dispatch/middleware/static.rb:127:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rack-028438ffffd9/lib/rack/sendfile.rb:111:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/railties/lib/rails/engine.rb:525:in `call'
   () Users/berry/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/rails-9b16b4997712/railties/lib/rails/application.rb:165:in `call'
  puma (2.14.0) lib/puma/server.rb:541:in `handle_request'
  puma (2.14.0) lib/puma/server.rb:388:in `process_client'
  puma (2.14.0) lib/puma/server.rb:270:in `block in run'
  puma (2.14.0) lib/puma/thread_pool.rb:106:in `block in spawn_thread'

**Comment by pwnall** [comment]
This merits a separate bug.
